name: Production Workflow

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'
<<<<<<< HEAD:.github/workflows/prod.yml
=======
  pull_request:
    branches:
      - 'master'
      - 'main'
>>>>>>> 88d84f05d85ff5c804d3954c3c5643c0c87c0e67:.github/workflows/test-build-deploy.yml

jobs:
  runtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jk262/is218

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
<<<<<<< HEAD:.github/workflows/prod.yml
          heroku_app_name: "kwilliam-prod" #Must be unique in Heroku
          heroku_email: "keith@webizly.com"
=======
          heroku_app_name: "jkowal-flask" #Must be unique in Heroku
          heroku_email: "jk262@njit.edu"
>>>>>>> 88d84f05d85ff5c804d3954c3c5643c0c87c0e67:.github/workflows/test-build-deploy.yml
          usedocker: true